export const SET_IDENTITY = 'SET_IDENTITY'
export const RESET_IDENTITY = 'RESET_IDENTITY'
export const SET_PUBLIC_IDENTITY = 'SET_PUBLIC_IDENTITY'
export const RESET_PUBLIC_IDENTITY = 'RESET_PUBLIC_IDENTITY'
export const ADD_CREDENTIAL = 'ADD_CREDENTIAL'
export const DELETE_ALL_CREDENTIALS = 'DELETE_ALL_CREDENTIALS'
export const UPDATE_CREDENTIAL_STATUS = 'UPDATE_CREDENTIAL_STATUS'
// TODO multiline comments
