export const APP_STARTUP = 'AppStartup'
// Setup (first-time)
export const IDENTITY_SETUP = 'IdentitySetup'
export const MNEMONIC_CREATION = 'MnemonicCreation'
export const INTRODUCTION = 'Introduction'
export const USERNAME_SETUP = 'UsernameSetup'
// Main app
export const APP = 'App'
export const SETUP = 'Setup'
export const DASHBOARD = 'Dashboard'
export const NEW_CLAIM = 'NewClaim'
export const SEND_FOR_VERIFICATION = 'SendForVerification'
export const SETTINGS = 'Settings'
export const CONTACTS = 'Contacts'
export const ACCOUNT = 'Account'
export const DEVICE = 'Device'
